# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Devel-TrackObjects
version:      0.1
version_from: lib/Devel/TrackObjects.pm
installdirs:  site
requires:
    Scalar::Util:                  1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
